### ISSUE TITLE
gdevilspie will not open in Xubuntu 13.10

### ISSUE THREAD

**Issue by GoogleCodeExporter** [schuellerf/gdevilspie#21]
```
What steps will reproduce the problem?
1. Attempt to open gdevilspie 

What is the expected output? What do you see instead?

Expected output: a GUI. What I see: nothing

What version of the product are you using? On what operating system?
gdevilspie 1:0.5-3
Xubuntu 13.10

Please provide any additional information below.

Attempting to open gdevilspie via the terminal gives the following error 
message:

Traceback (most recent call last):
  File "/usr/bin/gdevilspie", line 893, in <module>
    MainWindow = RulesListWindow()
  File "/usr/bin/gdevilspie", line 374, in __init__
    self.UpdateAutostartStatus()
  File "/usr/bin/gdevilspie", line 545, in UpdateAutostartStatus
    if (os.path.exists(xdg.DesktopEntry.xdg_config_home + "/autostart/devilspie.desktop")):
AttributeError: 'module' object has no attribute 'xdg_config_home'


```

Original issue reported on code.google.com by `matthewm...@gmail.com` on 21 Mar 2014 at 5:40

**Comment by GoogleCodeExporter** [comment]
```
same error in ubuntu 13.10 kernel 3.11.0-19
~/tools/gdevilspie-0.5$ ./gdevilspie 
Gtk-Message: Failed to load module "overlay-scrollbar"
Traceback (most recent call last):
  File "./gdevilspie", line 893, in <module>
    MainWindow = RulesListWindow()
  File "./gdevilspie", line 374, in __init__
    self.UpdateAutostartStatus()
  File "./gdevilspie", line 545, in UpdateAutostartStatus
    if (os.path.exists(xdg.DesktopEntry.xdg_config_home + "/autostart/devilspie.desktop")):
AttributeError: 'module' object has no attribute 'xdg_config_home'
```

Original comment by `gsus...@gmail.com` on 2 Apr 2014 at 3:07

**Comment by GoogleCodeExporter** [comment]
```
Sorry I saw the patch and it fixes the problem.
```

Original comment by `gsus...@gmail.com` on 2 Apr 2014 at 3:15

**Comment by GoogleCodeExporter** [comment]
```
Hi,
I had a comment with a patch on issue 22.
```

Original comment by `tuxmoura...@gmail.com` on 29 May 2014 at 1:30

**Comment by GoogleCodeExporter** [comment]
```
I just saw the patch on issue 20, same as mine.
```

Original comment by `tuxmoura...@gmail.com` on 29 May 2014 at 1:32
